apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab3ingress
spec:
  tls:
  - hosts:
    - ellechkka.com  
    secretName: app-tls
  rules:
  - host: ellechkka.com   
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lab3service
            port:
              number: 3000